### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by monk-time**
Hi!

I've been working hard for the last month on rewriting the script to modernize the code and remove jQuery dependancy. It no longer depends on jQuery and its plugins (so e.g. the main modal window is now purely native), the very confusing way settings were handled has been untangled and cleaned up, and lots of stuff have been renamed and reorganized. Also I decided to use localStorage instead of GM APIs to avoid the whole GM4 mess and make the script GM-compatible again.

There are also dozens of minor changes and additions, the more noticeable ones are mentioned in the changelog. 

I'm really proud of how the script turned out. Many rough edges (like the mess I introduced many years ago with settings/options/config/cfg) have been smoothed out, every corner has been revisited. The whole shebang now is crispy clean. :)

### CODE REVIEW

**Comment by monk-time** [comment]
Thank you!

Since we've been doing this for quite a long time, what do you think about adding me as a collaborator for the repo? That way I'll be able to push changes to the script directly without opening a PR.

**Comment by monk-time** [comment]
For some reason [GreasyFork](https://greasyfork.org/en/scripts/11541-icheckmovies-enhanced) still shows the old version. Maybe something happened to GitHub syncing? It used to auto-update AFAIR.

**Comment by labyrinthofdreams** [comment]
It's set to auto-sync from this repo. When I try to manually sync, it complains about this:

`Script sync failed - Code contains errors: Uncaught SyntaxError: Unexpected token '??=' at undefined:1567:36.`

**Comment by monk-time** [comment]
Oh, that again. I guess I'll have to rewrite that bit. No idea why greasyfork even cares about script syntax.

**Pull request merged**
